# Site settings
title: Inflection Point
header-img: img/home-bg.png
email: ryan.walberg@gmail.com
copyright_name: walbergr
description: > # this means to ignore newlines until "baseurl:"
  At an inflection point in life.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  walbergr
learn_profile: walbergr
email_username: ryan.walberg@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
